name = "IdentityRanges"
uuid = "bbac6d45-d8f3-5730-bfe4-7a449cd117ca"
author = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.3.1"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
OffsetArrays = "0.10, 0.11, 1"
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
